/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fy_administrator_jnitoso_JniUtil */

#ifndef _Included_com_fy_administrator_jnitoso_JniUtil
#define _Included_com_fy_administrator_jnitoso_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fy_administrator_jnitoso_JniUtil
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fy_administrator_jnitoso_JniUtil_init
  (JNIEnv *, jobject);

/*
 * Class:     com_fy_administrator_jnitoso_JniUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fy_administrator_jnitoso_JniUtil_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_fy_administrator_jnitoso_JniUtil
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fy_administrator_jnitoso_JniUtil_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
